package HelloWorld.HelloWorldApp;

/**
* HelloWorldApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* samedi 25 octobre 2025 18 h 01 WET
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorld.HelloWorldApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (HelloWorld.HelloWorldApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorld.HelloWorldApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
	  HelloWorld.HelloWorldApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorld.HelloWorldApp.HelloHelper.type ();
  }

}
